In [1]:
import tensorflow as tf

2025-05-07 11:19:47.616582: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-07 11:19:47.626213: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-07 11:19:47.757064: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-07 11:19:47.896142: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1746609588.009779   16583 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746609588.04

In [2]:
print(tf.__version__)

2.19.0


In [3]:
scalar = tf.constant(1)
scalar, scalar.ndim

2025-05-07 11:19:54.395023: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


(<tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

In [4]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [5]:
matrix = tf.constant([[10, 7], [7,10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 2)

In [6]:
another_matrix = tf.constant([[11, 20],[5, 13], [8, 9]], dtype=tf.float16)
another_matrix, another_matrix.dtype

2025-05-07 11:19:54.433297: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[11., 20.],
        [ 5., 13.],
        [ 8.,  9.]], dtype=float16)>,
 tf.float16)

In [7]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 3)

In [8]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [9]:
changeable_tensor[0].assign(1)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [10]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

# Rand tensors

In [11]:
random_1 = tf.random.Generator.from_seed(7)
random_3 = random_1.normal(shape=(3,2))
random_4 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
random_4, random_3, random_2, random_3 == random_2, random_4 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.15951356, -0.2555016 ],
        [ 1.4733889 , -1.8130383 ],
        [-0.693323  ,  0.61685944]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [12]:
random_1 = tf.random.Generator.from_seed(7)
random_3 = random_1.normal(shape=(3,2))
random_4 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

In [13]:
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
tf.random.set_seed(3)
tf.random.shuffle(not_shuffled, seed=42), tf.random.shuffle(not_shuffled, seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 2,  5],
        [10,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

### Other ways to make tensors

In [14]:
#Create tensor of all ones and zeros
tf.ones((3,2)), tf.zeros((10,9))

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(10, 9), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

### Turn NumPy arrays into tensors

Main difference between Numpy array and TensorFlow tensor is that tensor can be run on GPU

In [15]:
# Numpy to tensor

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
# X = tf.constant(some_matrix) # capital letter matrix or tensor
# y = tf.constant(some_vector) # small letter vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [16]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting info from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [17]:
A_rand = tf.random.Generator.from_seed(7)
A = A_rand.normal((3,2,4,5))
A = tf.zeros((2,3,4,5))
A

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
A.dtype, A.shape, A.ndim, A[0], A[:, 1], tf.size(A).numpy(), A.shape[0], A.shape[-1]

(tf.float32,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 np.int32(120),
 2,
 5)

### Indexing tensors

Tensors can be index like python list

In [19]:
# Get the first two elements of each dimension in tensor

A[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Get the first element from each dimension from each index except for the final one

A[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
# Create rank 2 tensor

B = tf.zeros((10,7))

In [22]:
B.shape

TensorShape([10, 7])

In [23]:
B[:, -1]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [24]:
# Add in extra dimension to rank 2 tensor
C = B[..., tf.newaxis] # => C = B[: ,: , tf.newaxis]
C

<tf.Tensor: shape=(10, 7, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
      

In [25]:
B[: , tf.newaxis,: ]

<tf.Tensor: shape=(10, 1, 7), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
# Alternative to tf.newaxis
tf.expand_dims(B, axis=1)

<tf.Tensor: shape=(10, 1, 7), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

### Manipulate tensors

**Basic operations**

`+`, `-`, `*`, `/`

In [27]:
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [28]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [29]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [30]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [31]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10) # typically the operation got sped up on GPU if tf function used, so it's better to used TF functions instead of overloaded operators
# I just read about it in GEMINI, turns out, that either way works the same, the built-in functions are better at keeping code consistent and readable. 
# It also gives some parameters that sometimes can't be accessed via overloaded operator.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [32]:
tensor ** 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

### Matrix multiplication
One of the most common tensor operations in ML. Element-wise (before while multiplying by scalar), Dot product (Now)

In [33]:
# Matrix multiplication in tensorflow, matmul
dot_product = tf.matmul(tensor,tensor)
element_wise = tensor * tensor
dot_product, element_wise

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]], dtype=int32)>)

In [34]:
# Matrix multiplication with python operator "@"
tensor_a = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_b = tf.constant([[3, 5],[6,7],[1,8]])
tensor_a, tensor_b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [35]:
tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [36]:
tensor_a @ tensor_b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [37]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [38]:
try:
    X @ Y
except tf.errors.InvalidArgumentError as e:
    print(f"{e},\n {e.experimental_payloads}")

{{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: ,
 {}


2025-05-07 11:19:54.769104: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2]


In [39]:
Z = tf.reshape(Y, (2, 3))
X@Z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [40]:
# Transpose in compare to reshape
X, tf.transpose(X), tf.reshape(X, (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [41]:
tf.transpose(X) @ Y, tf.reshape(X, (2,3)) @ Y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]], dtype=int32)>)

### Dot product different functions

* `tf.matmul`
* `tf.tensordot`

In [42]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [43]:
tf.matmul(X, tf.transpose(Y)), tf.matmul(X, tf.reshape(Y, (2,3)))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [44]:
tf.reduce_sum(tf.matmul(X, tf.transpose(Y))), tf.reduce_sum(tf.matmul(X, tf.reshape(Y, (2,3))))

(<tf.Tensor: shape=(), dtype=int32, numpy=603>,
 <tf.Tensor: shape=(), dtype=int32, numpy=612>)

In [45]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [46]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [49]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype, B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

#### important concept!
Casting the datatype to 16bit equivalent is potential speed up the computation on hardware, given cutting the space that the tensor takes in memory.

In [50]:
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [51]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors is condensing the tensor from bigger to smaller based on some function

In [ ]:
# Get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Few other aggregations:
* get min
* get max
* get mean
* get sum

In [65]:
import tensorflow_probability as tfp

In [68]:
tf.reduce_sum(D), tf.reduce_mean(D), tf.reduce_max(D), tf.reduce_min(D), tf.math.reduce_std(tf.cast(D, dtype=tf.float16)), tf.math.reduce_variance(tf.cast(D, dtype=tf.float16)), tfp.stats.variance(tf.cast(D, dtype=tf.float16))

(<tf.Tensor: shape=(), dtype=int32, numpy=-17>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-10>,
 <tf.Tensor: shape=(), dtype=float16, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float16, numpy=2.25>,
 <tf.Tensor: shape=(), dtype=float16, numpy=2.25>)

### Find the positional maximum and minimum

In [70]:
tf.math.argmin(D), tf.math.argmax(D)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [74]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=(50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [76]:
tf.math.argmin(F), tf.math.argmax(F), F[tf.math.argmin(F)], F[tf.math.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

### Squeezing a tensor
Remove all single dimensions

In [79]:
# Create a tensor
G = tf.constant(tf.random.uniform(shape=(50,)), shape=(1,1,1,1,50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
            0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
            0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
            0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
            0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
            0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
            0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
            0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
            0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
            0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [80]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
        0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
        0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
        0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
        0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
        0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
        0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
        0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
        0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
        0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

Preparing data concept in ML/AI


In [87]:
# Create list of indices
some_list = [0,1,2,3,2,3,1,0,2,2,3,1,1,1,3,0]

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(16, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]], dtype=float32)>

In [89]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=5, on_value="x", off_value='o')

<tf.Tensor: shape=(16, 5), dtype=string, numpy=
array([[b'x', b'o', b'o', b'o', b'o'],
       [b'o', b'x', b'o', b'o', b'o'],
       [b'o', b'o', b'x', b'o', b'o'],
       [b'o', b'o', b'o', b'x', b'o'],
       [b'o', b'o', b'x', b'o', b'o'],
       [b'o', b'o', b'o', b'x', b'o'],
       [b'o', b'x', b'o', b'o', b'o'],
       [b'x', b'o', b'o', b'o', b'o'],
       [b'o', b'o', b'x', b'o', b'o'],
       [b'o', b'o', b'x', b'o', b'o'],
       [b'o', b'o', b'o', b'x', b'o'],
       [b'o', b'x', b'o', b'o', b'o'],
       [b'o', b'x', b'o', b'o', b'o'],
       [b'o', b'x', b'o', b'o', b'o'],
       [b'o', b'o', b'o', b'x', b'o'],
       [b'x', b'o', b'o', b'o', b'o']], dtype=object)>

### Square, log, square root

In [90]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [93]:
tf.square(H), tf.sqrt(tf.cast(H, dtype=tf.float16)), tf.math.log(tf.cast(H, dtype=tf.float16))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
       dtype=float16)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
        2.197 ], dtype=float16)>)

### Tensors and NumPy

TensorFlow interacts great with Numpy arrays<br>
TensorFlow can be run on GPU or TPU in compare to Numpy, so speed up math

In [96]:
J = tf.constant(np.array([3.,4.,7.]))
J, type(J), np.array(J), type(np.array(J))

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 7.])>,
 tensorflow.python.framework.ops.EagerTensor,
 array([3., 4., 7.]),
 numpy.ndarray)

In [99]:
J[0], J.numpy()[0]

(<tf.Tensor: shape=(), dtype=float64, numpy=3.0>, np.float64(3.0))

In [101]:
J_from_numpy = tf.constant(np.array([3.,4.,5.]))
J_from_list = tf.constant([3.,4.,5.])

J_from_numpy.dtype, J_from_list.dtype # be aware of different dtypes when we switch to numpy

(tf.float64, tf.float32)

### Find access to GPU
Probably to run on my PC


In [102]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [107]:
x = [1., 2., 3., 4., 5.]
y = [0., 2., 3., 5., 5.]
equality= tf.equal(x,y)
equality_cast = tf.cast(equality,tf.float32)
equality_bitcast = tf.bitcast(equality_cast,tf.uint8)
equality, equality_cast, equality_bitcast

(<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True, False,  True])>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 1., 0., 1.], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=uint8, numpy=
 array([[  0,   0,   0,   0],
        [  0,   0, 128,  63],
        [  0,   0, 128,  63],
        [  0,   0,   0,   0],
        [  0,   0, 128,  63]], dtype=uint8)>)